# Generated by Django 4.1.2 on 2023-01-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_waitlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlist',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
