# Generated by Django 4.1.2 on 2023-03-08 14:30

import SmartCarteApi.common
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_waitlist_first_name_alter_waitlist_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('datetime_created', models.DateTimeField(default=SmartCarteApi.common.get_utc_datetime_now)),
                ('datetime_deleted', models.DateTimeField(null=True)),
                ('tid', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='waitlist',
            name='demo_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_signups', to='account.demouser'),
        ),
    ]
