

TASK_STATUS_PENDING = "pending"
TASK_STATUS_RUNNING = "running"
TASK_STATUS_CANCELED = "canceled"
TASK_STATUS_COMPLETE = "complete"
TASK_STATUS_FAILED = "failed"

TASK_STATUSES = [
    TASK_STATUS_PENDING, 
    TASK_STATUS_RUNNING,
    TASK_STATUS_CANCELED,
    TASK_STATUS_COMPLETE,
    TASK_STATUS_FAILED
]
