

TASK_STATUS_PENDING = "pending"
TASK_STATUS_RUNNING = "running"
TASK_STATUS_CANCELED = "canceled"
TASK_STATUS_COMPLETE = "complete"
TASK_STATUS_FAILED = "failed"

TASK_STATUSES = [
    TASK_STATUS_PENDING, 
    TASK_STATUS_RUNNING,
    TASK_STATUS_CANCELED,
    TASK_STATUS_COMPLETE,
    TASK_STATUS_FAILED
]


TASK_TYPE_BURN_AREAS = "burn_areas"
TASK_TYPE_FOREST_CHANGE = "forest_change"
TASK_TYPE_LULC_CHANGE = "lulc_change"
TASK_TYPE_LULC_CLASSIFICATION = "lulc_classification"

TASK_TYPES = [
    TASK_TYPE_BURN_AREAS,
    TASK_TYPE_FOREST_CHANGE,
    TASK_TYPE_LULC_CHANGE,
    TASK_TYPE_LULC_CLASSIFICATION
]