# Generated by Django 4.1.2 on 2023-01-04 15:55

import SmartCarteApi.common
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForestChangeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('datetime_created', models.DateTimeField(default=SmartCarteApi.common.get_utc_datetime_now)),
                ('datetime_updated', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('gain_area', models.IntegerField(null=True)),
                ('loss_area', models.IntegerField(null=True)),
                ('total_area', models.IntegerField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forest_change_tasks', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forest_change_tasks', to='account.organization')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='account.region')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
