# Generated by Django 4.1.2 on 2023-01-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forestchangetask',
            name='datetime_completed',
            field=models.DateTimeField(null=True),
        ),
    ]
