# Generated by Django 4.1.2 on 2023-01-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_forestchangetask_datetime_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='forestchangetask',
            name='after_rgb_tiles_href',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='forestchangetask',
            name='before_rgb_tiles_href',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='forestchangetask',
            name='change_tiles_href',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='forestchangetask',
            name='status_message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='forestchangetask',
            name='type',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
