# Generated by Django 4.1.2 on 2023-03-08 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_demouser_waitlist_demo_user'),
        ('tasks', '0004_demolandcoverclassificationtask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demolandcoverclassificationtask',
            name='demo_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demo_classification_tasks', to='account.demouser'),
        ),
        migrations.AlterField(
            model_name='demolandcoverclassificationtask',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='demolandcoverclassificationtask',
            name='imagery_tif_href',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='demolandcoverclassificationtask',
            name='imagery_tiles_href',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='demolandcoverclassificationtask',
            name='landcover_tif_href',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='demolandcoverclassificationtask',
            name='landcover_tiles_href',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
