# Generated by Django 4.1.2 on 2023-03-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_demolandcoverclassificationtask_status_long_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demolandcoverclassificationtask',
            name='statistics_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
