# Generated by Django 4.1.2 on 2023-04-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_demolandcoverclassificationtask_rgb_tif_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='demolandcoverclassificationtask',
            name='slug',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
